root = "."
#the root directory of the project
tmp_dir = "tmp"
#the temporary directory where air will store it's temporary files
#the build configuration
[build]
    bin = "main"
    #name of the binary file to be generated after building the project
    cmd = "go build -o {{.Output}}{{.Input}}"
    #the command to build the project
    exclude = ["tmp/*","client/*","client/node_modules/*"]
    #specifies the directories to be excluede from
    #monitoring for changes
    include = ["**/*.go"]
    #specifies the file patterns to be included for monitoring
    ignore = ["tmp/*","client/*"]
    #specifies the files or directories to be ignores when
    #triggering a build
